amcl:
  ros__parameters:
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.2

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    min_vel_x: 0.0
    max_vel_x: 0.26
    max_vel_theta: 1.82
